openapi: "3.0.3"
info:
  title: MD-3-User 帳號管理API
  description: |
    帳號及角色權限管理模組，系統管理者使用的帳號管理API。  
    
    ## API清單：
    * MD-3-User-Create 帳號-建立單筆。供管理員可手動建立帳號。
    * MD-3-User-Get 帳號-查詢單筆。
    * MD-3-User-Update 帳號-更新單筆。供管理員更新主帳號。
    * MD-3-User-Remove 帳號-刪除單筆。供管理員刪除主帳號。
    * MD-3-User-List 帳號-查詢多筆。供管理員查詢主帳號清單。
    * MD-3-User-Export 帳號-匯出excel。
    * MD-3-User-ChangePassword 登入者帳號-變更密碼。供個人使用。
    
    ## 非200狀態回應說明
    目前定義的異常狀態如下，以下狀態於各API回應內容格式皆相同，因此各API預設只描述正常 200 的回應情況。
    * 請求格式錯誤。 http status code 400。
    * 指定的錯誤訊息或是缺少參數。 http status code 401。
    * 操作權限不足。 http status code 403。
    * 請求的資源不存在。 http status code 404。
    * 伺服端錯誤。 http status code 500。

  version: "1.0"
servers:
  - url: "{baseUrl}/star/api/user/{version}"
    variables:
      baseUrl:
        description: 主機網址
        default: 'localhost:8086'
      version:
        description: 版號
        default: "v1"
paths:
  /:
    get:
      tags:
        - MD-3-User
      summary: MD-3-User-Get
      description: 帳號-查詢單筆。
      operationId: MD-3-User-Get
      parameters:
        - $ref: '#/components/parameters/noCacheHeader'
        - $ref: '#/components/parameters/jsonContentTypeHeader'
        - $ref: '#/components/parameters/idParam'
        - $ref: '#/components/parameters/pgIdParam'
      responses:
        '200':
          description: 正常執行完成。
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/RespBase'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/UserGetResp'
  /create:
    post:
      tags:
        - MD-3-User
      summary: MD-3-User-Create
      description: |
        帳號-建立單筆。管理員可手動建立帳號。  
        管理員建立主帳號時，不需輸入密碼。由該帳號自行透過忘記密碼來變更密碼。
      operationId: MD-3-User-Create
      parameters:
        - $ref: '#/components/parameters/noCacheHeader'
        - $ref: '#/components/parameters/jsonContentTypeHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateReq'
      responses:
        '200':
          $ref: '#/components/responses/IdSimpleResponse'
  /update:
    post:
      tags:
        - MD-3-User
      summary: MD-3-User-Update
      description: 帳號-更新單筆。供管理員更新主帳號。
      operationId: MD-3-User-Update
      parameters:
        - $ref: '#/components/parameters/noCacheHeader'
        - $ref: '#/components/parameters/jsonContentTypeHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateReq'
      responses:
        '200':
          $ref: '#/components/responses/IdSimpleResponse'
  /remove:
    post:
      tags:
        - MD-3-User
      summary: MD-3-User-Remove
      description: |
        帳號-刪除單筆。供管理員刪除主帳號。  
        刪除時標記為已刪除，但資料仍保存於資料庫中。
      operationId: MD-3-User-Remove
      parameters:
        - $ref: '#/components/parameters/noCacheHeader'
        - $ref: '#/components/parameters/jsonContentTypeHeader'
        - $ref: '#/components/parameters/idParam'
        - $ref: '#/components/parameters/pgIdParam'
      responses:
        '200':
          $ref: '#/components/responses/IdSimpleResponse'
  /list:
    post:
      tags:
        - MD-3-User
      summary: MD-3-User-List
      description: | 
        帳號-查詢多筆。供管理員查詢主帳號清單。  
        不支援模糊援尋的查詢條件，包括：帳號、姓名。其它文字輸入類型的欄位可支援模糊援尋。
      operationId: MD-3-User-List
      parameters:
        - $ref: '#/components/parameters/noCacheHeader'
        - $ref: '#/components/parameters/jsonContentTypeHeader'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserListReq'
      responses:
        '200':
          description: 正常執行完成。
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/RespBase'
                  - type: object
                    properties:
                      paging:
                        $ref: '#/components/schemas/Paging'
                      data:
                        description: 回應資料
                        type: array
                        items:
                          - $ref: '#/components/schemas/UserListResp'
  /export:
    post:
      tags:
        - MD-3-User
      summary: MD-3-User-Export
      description: 帳號-匯出excel。
      operationId: MD-3-User-Export
      parameters:
        - $ref: '#/components/parameters/noCacheHeader'
        - $ref: '#/components/parameters/jsonContentTypeHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserListReq'
      responses:
        '200':
          description: 正常執行完成。
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserBase:
      description: 系統帳號基本欄位
      properties:
        account:
          description: 帳號
          type: string
        password:
          description: 密碼
          type: string
        name:
          description: 姓名
          type: string
        telPhone:
          description: 電話
          type: string
        email:
          description: 電子郵件
          type: string
          format: email
        status:
          description: 狀態。停用0、啟用1。
          type: integer
    UserEntity:
      description: 系統帳號
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            id:
              description: 鍵值
              type: integer
            lastUpdatedTime:
              description: 最後修改時間
              type: string
              format: date-time
            lastUpdatedUserId:
              description: 最後修改人員之鍵值
              type: integer
            lastUpdatedUserName:
              description: 最後修改人員之鍵值
              type: string
    RoleEntity:
      description: 角色資料欄位。
      properties:
        roleId:
          description: 角色鍵值
          type: integer
        roleCode:
          description: 角色代碼
          type: string
          maxLength: 20
        roleName:
          description: 角色名稱
          type: string
          maxLength: 100
    UserCreateReq:
      description: 管理員建立主帳號。請求參數。
      required:
        - roleId
        - name
        - telPhone
        - email
        - account
        - status
        - password
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            roleId:
              description: 角色鍵值
              type: integer
    UserGetResp:
      description: 查詢單筆主帳號，回應內容。
      allOf:
        - $ref: '#/components/schemas/UserEntity'
        - $ref: '#/components/schemas/RoleEntity'
    UserUpdateReq:
      description: 管理員更新主帳號，請求參數。
      required:
        - id
      properties:
        id:
          description: 鍵值
          type: integer
        name:
          description: 姓名
          type: string
        telPhone:
          description: 電話
          type: string
        email:
          description: 電子郵件
          type: string
          format: email
        status:
          description: 狀態。停用0、啟用1。
          type: integer
        roleId:
          description: 角色鍵值
          type: integer
        password:
          description: 密碼
          type: string
    UserListReq:
      description: 查詢主帳號列表清單，回應內容。
      properties:
        account:
          description: 帳號。不支援模糊搜尋。
          type: string
        name:
          description: 姓名。不支援模糊搜尋。
          type: string
        roleId:
          description: 角色鍵值
          type: integer
        status:
          description: 停用或啟用。 停用0、啟用1。
          type: integer
    UserListResp:
      description: 主帳號列表查詢，回應內容。
      properties:
        id:
          description: 鍵值
          type: integer
        account:
          description: 帳號
          type: string
        name:
          description: 姓名
          type: string
        roleName:
          description: 角色名稱
          type: string
        status:
          description: 狀態。停用0、啟用1。
          type: integer
        lastLoginTime:
          description: 最後登入時間
          type: string
          format: date-time
    IdSimpleResp:
      description: 只回應資料鍵值及名稱。
      type: object
      properties:
        id:
          description: 鍵值
          type: integer
        subject:
          description: id對應的標的的名稱
          type: string
    SimpleResp:
      description: 只回應資料鍵值及名稱。
      type: object
      properties:
        uid:
          description: 鍵值
          type: string
          format: uuid
        subject:
          description: uid對應的標的的名稱
          type: string
    RespBase:
      type: object
      properties:
        code:
          type: integer
          description: |
            錯誤代碼: 
            * `0` : 成功
            * `1xxx` : 參數錯誤
            * `2xxx` : 權限不合法或資料不存在
            * `3xxx` : 系統異常
        message:
          type: string
          description: 錯誤訊息
    Paging:
      description: 分頁資訊
      type: object
      properties:
        offset:
          description: 查詢分頁的 offset
          type: integer
        limit:
          description: 查詢分頁的 limit
          type: integer
        total:
          description: 資料總筆數
          type: number
    TimeRange:
      description: 時間區間。有開始及結束時間。
      type: object
      properties:
        startTime:
          description: 開始時間
          type: string
          format: date-time
        endTime:
          description: 結束時間
          type: string
          format: date-time
  parameters:
    pgIdParam:
      description: 機關群組鍵值
      name: pgId
      in: query
      required: true
      schema:
        type: integer
    idParam:
      description: 鍵值參數
      name: id
      in: query
      required: true
      schema:
        type: integer
    uidParam:
      description: 鍵值參數
      name: uid
      in: query
      required: true
      schema:
        type: string
        format: uuid
    apiKeyHeader:
      description: 系統發佈給應用程式使用的 API Key。
      name: X-API-Key
      in: header
      required: true
      schema:
        type: string
    accessTokenHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
        example: 'Bearer {accessToken}'
    offsetParam:
      description: 查詢分頁的 offset。與 limit 搭配使用。
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 0
    limitParam:
      description: 查詢分頁的 limit。與 offset 搭配使用。
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 20
    noCacheHeader:
      name: Cache-Control
      in: header
      required: true
      schema:
        type: string
        default: no-cache
    jsonContentTypeHeader:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
  responses:
    IdSimpleResponse:
      description: 正常執行完成，並回應 uid 及 subject。
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/RespBase'
              - type: object
                properties:
                  data:
                    description: 回應資料
                    allOf:
                      - $ref: '#/components/schemas/IdSimpleResp'
    SimpleResponse:
      description: 正常執行完成，並回應 uid 及 subject。
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/RespBase'
              - type: object
                properties:
                  data:
                    description: 回應資料
                    allOf:
                      - $ref: '#/components/schemas/SimpleResp'
    MultiSimpleResponse:
      description: 正常執行完成，並回應多筆 SimpleResp。
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/RespBase'
              - type: object
                properties:
                  data:
                    description: 回應資料
                    type: array
                    items:
                      $ref: '#/components/schemas/SimpleResp'
    400ErrorResponse:
      description: 請求格式錯誤。 http status code 400。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RespBase'
    401ErrorResponse:
      description: 缺少 ApiKey, AccessToken 或是驗證失敗。 http status code 401。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RespBase'
    403ErrorResponse:
      description: 操作權限不足。 http status code 403。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RespBase'
    404ErrorResponse:
      description: 請求的資源不存在。 http status code 404。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RespBase'
    500ErrorResponse:
      description: 伺服端錯誤。 http status code 500。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RespBase'

